"""Back to normal

Revision ID: 1d48530845b8
Revises: 8e50233b73cb
Create Date: 2024-02-26 10:47:11.641614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d48530845b8'
down_revision: Union[str, None] = '8e50233b73cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('master', 'course_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('master', sa.Column('course_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
