"""Changing Master Table

Revision ID: 3448a432474e
Revises: ccf3fc6a9d5c
Create Date: 2024-02-26 10:40:48.481560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3448a432474e'
down_revision: Union[str, None] = 'ccf3fc6a9d5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('master', sa.Column('course_name', sa.String(), nullable=True), insert_after='tournament_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('master', 'course_name')
    # ### end Alembic commands ###
