"""Adding Courses Column to Tourns

Revision ID: 46601875ae64
Revises: 4d5570b3947f
Create Date: 2024-02-28 19:55:47.135832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46601875ae64'
down_revision: Union[str, None] = '4d5570b3947f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournament', sa.Column('tourney_name', sa.String(), nullable=False))
    op.add_column('tournament', sa.Column('tourney_id', sa.String(), nullable=True))
    op.add_column('tournament', sa.Column('course_name', sa.String(), nullable=True))
    op.drop_index('ix_tournament_name', table_name='tournament')
    op.create_index(op.f('ix_tournament_tourney_name'), 'tournament', ['tourney_name'], unique=False)
    op.drop_column('tournament', 'id')
    op.drop_column('tournament', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournament', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('tournament', sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_tournament_tourney_name'), table_name='tournament')
    op.create_index('ix_tournament_name', 'tournament', ['name'], unique=False)
    op.drop_column('tournament', 'course_name')
    op.drop_column('tournament', 'tourney_id')
    op.drop_column('tournament', 'tourney_name')
    # ### end Alembic commands ###
