"""Adding Odds column

Revision ID: 4d5570b3947f
Revises: ad8d76f7dace
Create Date: 2024-02-28 18:40:30.443002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d5570b3947f'
down_revision: Union[str, None] = 'ad8d76f7dace'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('master', sa.Column('odds', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('master', 'odds')
    # ### end Alembic commands ###
