"""empty message

Revision ID: 9f38fb67e882
Revises: bea3d5ebd5aa
Create Date: 2023-12-13 20:24:02.416515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f38fb67e882'
down_revision: Union[str, None] = 'bea3d5ebd5aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('schedule_tournament_name_fkey', 'schedule', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('schedule_tournament_name_fkey', 'schedule', 'tournament', ['tournament_name'], ['name'])
    # ### end Alembic commands ###
