"""just trying shit pt4

Revision ID: ad8d76f7dace
Revises: 8eaa8cd142d5
Create Date: 2024-02-26 14:17:23.384987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ad8d76f7dace'
down_revision: Union[str, None] = '8eaa8cd142d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_stats',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=True),
    sa.Column('sg_total', sa.Float(), nullable=True),
    sa.Column('sg_ttg', sa.Float(), nullable=True),
    sa.Column('sg_ott', sa.Float(), nullable=True),
    sa.Column('sg_apr', sa.Float(), nullable=True),
    sa.Column('sg_atg', sa.Float(), nullable=True),
    sa.Column('sg_putt', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_index(op.f('ix_player_stats_name'), 'player_stats', ['name'], unique=False)
    op.drop_index('ix_player_statss_name', table_name='player_statss')
    op.drop_table('player_statss')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_statss',
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('sg_total', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('sg_ttg', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('sg_ott', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('sg_apr', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('sg_atg', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('sg_putt', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('name', name='player_statss_pkey')
    )
    op.create_index('ix_player_statss_name', 'player_statss', ['name'], unique=False)
    op.drop_index(op.f('ix_player_stats_name'), table_name='player_stats')
    op.drop_table('player_stats')
    # ### end Alembic commands ###
