"""empty message

Revision ID: bea3d5ebd5aa
Revises: 89325d71da75
Create Date: 2023-12-13 17:56:07.291862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bea3d5ebd5aa'
down_revision: Union[str, None] = '89325d71da75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule', sa.Column('tourney_id', sa.String(), nullable=True))
    op.add_column('schedule', sa.Column('player_name', sa.String(), nullable=True))
    op.add_column('schedule', sa.Column('score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedule', 'score')
    op.drop_column('schedule', 'player_name')
    op.drop_column('schedule', 'tourney_id')
    # ### end Alembic commands ###
