"""im dumb2

Revision ID: c47bca9dd2d1
Revises: 752e0f3e31f9
Create Date: 2024-03-02 11:27:07.791375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c47bca9dd2d1'
down_revision: Union[str, None] = '752e0f3e31f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('tourney_id', sa.String(), nullable=True),
    sa.Column('tournament_name', sa.String(), nullable=True),
    sa.Column('course_name', sa.String(), nullable=True),
    sa.Column('player_id', sa.String(), nullable=True),
    sa.Column('player_name', sa.String(), nullable=True),
    sa.Column('finish', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('sg_total', sa.Float(), nullable=True),
    sa.Column('sg_ttg', sa.Float(), nullable=True),
    sa.Column('sg_ott', sa.Float(), nullable=True),
    sa.Column('sg_apr', sa.Float(), nullable=True),
    sa.Column('sg_atg', sa.Float(), nullable=True),
    sa.Column('sg_putt', sa.Float(), nullable=True),
    sa.Column('odds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_master_id'), 'master', ['id'], unique=False)
    op.drop_index('ix_masters_id', table_name='masters')
    op.drop_table('masters')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('masters',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tourney_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('tournament_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('course_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('player_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('player_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('finish', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sg_total', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('sg_ttg', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('sg_ott', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('sg_apr', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('sg_atg', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('sg_putt', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('odds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='masters_pkey')
    )
    op.create_index('ix_masters_id', 'masters', ['id'], unique=False)
    op.drop_index(op.f('ix_master_id'), table_name='master')
    op.drop_table('master')
    # ### end Alembic commands ###
