"""Add/Modify tables

Revision ID: ccf3fc6a9d5c
Revises: f8e05cd46998
Create Date: 2024-02-24 14:31:31.188959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccf3fc6a9d5c'
down_revision: Union[str, None] = 'f8e05cd46998'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
