"""Add course_name

Revision ID: e5628fbace02
Revises: 1d48530845b8
Create Date: 2024-02-26 10:47:41.483936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5628fbace02'
down_revision: Union[str, None] = '1d48530845b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('master', sa.Column('course_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('master', 'course_name')
    # ### end Alembic commands ###
