"""Adding Courses Column to Tourns

Revision ID: ec147ce1dd97
Revises: 46601875ae64
Create Date: 2024-02-28 19:59:54.821805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ec147ce1dd97'
down_revision: Union[str, None] = '46601875ae64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tournament2',
    sa.Column('tourney_name', sa.String(), nullable=False),
    sa.Column('tourney_id', sa.String(), nullable=True),
    sa.Column('course_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('tourney_name')
    )
    op.create_index(op.f('ix_tournament2_tourney_name'), 'tournament2', ['tourney_name'], unique=False)
    op.drop_index('ix_tournament_tourney_name', table_name='tournament')
    op.drop_table('tournament')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tournament',
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('tourney_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('tourney_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('course_name', sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.create_index('ix_tournament_tourney_name', 'tournament', ['tourney_name'], unique=False)
    op.drop_index(op.f('ix_tournament2_tourney_name'), table_name='tournament2')
    op.drop_table('tournament2')
    # ### end Alembic commands ###
