"""empty message

Revision ID: ef5937b6f35e
Revises: 9f38fb67e882
Create Date: 2023-12-13 20:26:24.599010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef5937b6f35e'
down_revision: Union[str, None] = '9f38fb67e882'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('schedule_player_id_fkey', 'schedule', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('schedule_player_id_fkey', 'schedule', 'player', ['player_id'], ['id'])
    # ### end Alembic commands ###
