"""Drop existing tables

Revision ID: f8e05cd46998
Revises: ef67f00eb3e5
Create Date: 2024-02-24 14:30:40.921500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f8e05cd46998'
down_revision: Union[str, None] = 'ef67f00eb3e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_schedule_id', table_name='schedule')
    op.drop_table('schedule')
    op.add_column('master', sa.Column('sg_total', sa.Float(), nullable=True))
    op.add_column('master', sa.Column('sg_ttg', sa.Float(), nullable=True))
    op.add_column('master', sa.Column('sg_ott', sa.Float(), nullable=True))
    op.add_column('master', sa.Column('sg_apr', sa.Float(), nullable=True))
    op.add_column('master', sa.Column('sg_atg', sa.Float(), nullable=True))
    op.add_column('master', sa.Column('sg_putt', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('master', 'sg_putt')
    op.drop_column('master', 'sg_atg')
    op.drop_column('master', 'sg_apr')
    op.drop_column('master', 'sg_ott')
    op.drop_column('master', 'sg_ttg')
    op.drop_column('master', 'sg_total')
    op.create_table('schedule',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tourney_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('tournament_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('player_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('player_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('finish', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='schedule_pkey')
    )
    op.create_index('ix_schedule_id', 'schedule', ['id'], unique=False)
    # ### end Alembic commands ###
